repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-merge-conflict # prevent committing files with merge conflicts
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.0 # Use the latest stable Ruff version
  hooks:
    - id: ruff-check # Runs the Ruff linter
      args: [ --fix ] # Optionally enable automatic fixes
    - id: ruff-format # Runs the Ruff formatter
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        args: [--ignore-words=.dictionary.txt]
        additional_dependencies:
        - tomli
-   repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)
        files: '^(bilby/bilby_mcmc/|bilby/core/sampler/|examples/)'

-   repo: https://github.com/datarootsio/databooks
    rev: 0.1.14
    hooks:
      - id: databooks
        name: databooks
        description:
          "Remove notebook metadata using `databooks`."
        entry: databooks meta
        language: python
        minimum_pre_commit_version: 2.9.2
        types: [ jupyter ]
        args: [-w]
-   repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
